name: Publish Quarto Website

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render HTML
        run: |
          quarto render lectures/1.md --to html -o _site/lectures/
          mkdir -p _site
          cp -r files _site/
          
          # Create a simple index.html that redirects to the lecture
          echo '<!DOCTYPE html>
          <html>
            <head>
              <meta http-equiv="refresh" content="0; url=lectures/1.html">
              <title>Redirecting...</title>
            </head>
            <body>
              <p>Redirecting to lecture...</p>
            </body>
          </html>' > _site/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site