name: Publish Quarto Website

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Install TinyTeX
        run: |
          quarto tools install tinytex
          
      - name: Install additional LaTeX packages
        run: |
          quarto tools install tinytex
          tlmgr update --self
          tlmgr install xetex
          tlmgr install fontspec
          tlmgr install unicode-math
          tlmgr install polyglossia
          tlmgr install cm-unicode
          tlmgr install adjustbox
          tlmgr install algorithm2e
          tlmgr install stmaryrd
          tlmgr install fontawesome5
          tlmgr install yfonts
          tlmgr install cancel

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}